name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo
          ~/.rustup
          target
        key: ${{ runner.os }}-cargo-checklist-${{ hashFiles('./Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-checklist-
          ${{ runner.os }}-cargo-

    - name: Add Rust to PATH
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "$HOME/.rustup/bin" >> $GITHUB_PATH

    - name: Install Rust
      run: |
        if [ -d "$HOME/.cargo/" ] && [ -d "$HOME/.rustup/" ]; then
            echo "Rust is already installed. Skipping installation."
        else
            echo "Rust is not installed. Installing via rustup..."
            curl https://sh.rustup.rs -sSf | sh -s -- -y
        fi

    - name: Show rust version
      run: rustc --version

    - name: Check formatting
      run: |
        cargo fmt --all --check || {
          echo "Formatting failed — please run 'cargo fmt --all' locally before pushing.";
          exit 1;
        }

    - name: Build
      run: cargo build --all-targets --all-features
      
    - name: Clippy
      run: RUSTFLAGS="-Dclippy::all" cargo clippy --all-targets --all-features -- -W clippy::pedantic -W clippy::nursery -W clippy::cargo

    - name: Run tests
      run: cargo test  --all-targets --all-features